---
filter_out_less_than_percentage: 85
filter_out_non_certified_fresh: true
filter_out_already_downloaded: true
filter_out_maximum_downloads: 5
comments:
    analyze: true
    quality: high # or low
    num_to_analyze: 10
    minimum_seeds: 50
download_directory: ~/Torrents
watch_file: /Users/admin/Sites/the_mobile_pirate/movies_to_download.txt